global:
  scrape_interval: 5s

scrape_configs:
  - job_name: detector
    static_configs:
      - targets: ["detector:8001"]
  - job_name: api
    metrics_path: /metrics/
    static_configs:
      - targets: ["api:8000"]
